name: Win PyTest

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, windows-2022 ]
        python-version: [ "3.13" ]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint ruff click httpx loguru piexif pillow pillow-heif tqdm numpy opencv-python packaging onnxruntime rembg
      - name: Run PyTest
        run: |
          pip install pytest-cov pytest-asyncio
          pytest --cov-report=term --cov=batch_img tests
